openapi: 3.0.0
info:
  title: Star Wars API
  description: API for retrieving information about planets in the Star Wars universe.
  version: "1.0"

paths:
  /planets:
    get:
      summary: Get all planets
      description: Retrieve a list of planets in the Star Wars universe.
      operationId: getAllPlanets
      responses:
        "200":
          description: A list of planets.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  total_records:
                    type: integer
                    example: 60
                  total_pages:
                    type: integer
                    example: 6
                  next:
                    type: string
                    example: "https://swapi.tech/api/planets?page=2&limit=10"
                  previous:
                    type: string
                    nullable: true
                    example: null
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Planet"

  /planets/{id}:
    get:
      summary: Get a planet by ID
      description: Retrieve details about a specific planet by its ID.
      operationId: getPlanetById
      parameters:
        - name: id
          in: path
          description: The ID of the planet to retrieve.
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Details of the planet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  result:
                    $ref: "#/components/schemas/PlanetDetail"

components:
  schemas:
    Planet:
      type: object
      properties:
        uid:
          type: string
          example: "1"
        name:
          type: string
          example: "Tatooine"
        url:
          type: string
          example: "https://www.swapi.tech/api/planets/1"

    PlanetDetail:
      type: object
      properties:
        properties:
          type: object
          properties:
            diameter:
              type: string
              example: "10465"
            rotation_period:
              type: string
              example: "23"
            orbital_period:
              type: string
              example: "304"
            gravity:
              type: string
              example: "1 standard"
            population:
              type: string
              example: "200000"
            climate:
              type: string
              example: "arid"
            terrain:
              type: string
              example: "desert"
            surface_water:
              type: string
              example: "1"
            created:
              type: string
              format: date-time
              example: "2024-12-17T15:23:44.809Z"
            edited:
              type: string
              format: date-time
              example: "2024-12-17T15:23:44.809Z"
            name:
              type: string
              example: "Tatooine"
            url:
              type: string
              example: "https://www.swapi.tech/api/planets/1"
        description:
          type: string
          example: "A planet."
        _id:
          type: string
          example: "5f7254c11b7dfa00041c6fae"
        uid:
          type: string
          example: "1"
        __v:
          type: integer
          example: 0
